version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: shoplist
      POSTGRES_PASSWORD: shoplist

  shoplist:
    build: .
    environment:
      DB_URL: "postgres://shoplist:shoplist@postgres:5432/shoplist"
    ports:
      - "3000:3000"
